### ISSUE TITLE
我的项目缺少 k4a_module.py 文件

### ISSUE THREAD

**Issue by z376368673** [etiennedub/pyk4a#75]
PS D:\python\pyk4a\example> python .\viewer_point_cloud.py
Traceback (most recent call last):
  File ".\viewer_point_cloud.py", line 62, in <module>
    main()
  File ".\viewer_point_cloud.py", line 41, in main
    points = capture.depth_point_cloud.reshape((-1, 3))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pyk4a\capture.py", line 
56, in depth_point_cloud
    self._depth_point_cloud = depth_image_to_point_cloud(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pyk4a\transformation.py", line 28, in depth_image_to_point_cloud
    calibration.transformation_handle, thread_safe, depth, calibration_type_depth,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pyk4a\calibration.py", line 118, in transformation_handle
    handle = k4a_module.transformation_create(self._calibration_handle, self.thread_safe)
NameError: name 'k4a_module' is not defined
PS D:\python\pyk4a\example> 

我也尝试添加了 
![image](https://user-images.githubusercontent.com/21307181/96997406-4bf21000-1564-11eb-830c-352f26a3e7bd.png)
添加了之后  运行 python .\viewe.py  没问题 
但是python .\viewer_point_cloud.py 仍然有错误

**Comment by z376368673** [comment]
上面图片的代码是 
from ctypes import c_wchar_p, windll  
from ctypes.wintypes import DWORD

AddDllDirectory = windll.kernel32.AddDllDirectory
AddDllDirectory.restype = DWORD
AddDllDirectory.argtypes = [c_wchar_p]
AddDllDirectory(r"C:\Program Files\Azure Kinect SDK v1.4.1\sdk\windows-desktop\amd64\release\bin")
